add proper permission for notify-docs-release job (#575)

diff --git a/.github/workflows/site.yml b/.github/workflows/site.yml
--- a/.github/workflows/site.yml
+++ b/.github/workflows/site.yml
@@ -121,6 +121,8 @@ jobs:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
   notify-docs-release:
     name: Notify Docs Release
+    permissions:
+      contents: write
     runs-on: ubuntu-latest
     continue-on-error: false
     needs:
@@ -141,7 +143,7 @@ jobs:
       run: |
         PACKAGE_NAME=$(cat docs/package.json | grep '"name"' | awk -F'"' '{print $4}')
         PACKAGE_VERSION=$(npm view $PACKAGE_NAME version)
-        curl -L \
+        response=$(curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: token ${{ steps.generate-token.outputs.token }}"\
@@ -152,4 +154,11 @@ jobs:
                     "package_name":"'"${PACKAGE_NAME}"'",
                     "package_version": "'"${PACKAGE_VERSION}"'"
                   }
-                }'
+                }')
+        
+        status_code=$(echo "$response" | jq -r '.status')
+        
+        if [ "$status_code" != "204" ]; then
+          echo "Error: Expected status code 204, got $status_code"
+          exit 1
+        fi
